### ISSUE TITLE
having an IOError when using oceansdb moduls

### ISSUE THREAD

**Issue by jichaojoyce** [castelao/oceansdb#11]
Does anyone has the similar issue as me having the IOError just following the documents' descriptions (as below):
import oceansdb
db = oceansdb.WOA()
db.keys()
t = db['sea_water_temperature'].extract(var='mean', doy=136.875, depth=0, lat=17.5, lon=-37.5)

Output: IOError: [Errno 13] Permission denied: 'c:\\users\\admini~1\\appdata\\local\\temp\\tmprxxkgz'

Does anyone know how to fix it?

**Comment by castelao** [comment]
Hi @jichaojoyce , sorry for the delay. It is always hard to catch up after being at sea without email.

Try to run in the terminal:
`  python -c "import oceansdb; oceansdb.WOA()['sea_water_temperature']"
`

It that fails, try to export the variable OCEANSDB_DIR pointing for a directory where would you like to have the WOA files stored, and try again the command above. I'm not sure how to do that on windows, but on Linux and OSX you could do:

`export OCEANSDB_DIR=/home/mydirectorywithwritingpermission/woa
`

I'm curious. I don't have access to any windows. Could do you a test, please? What do you get when you run in your Python:
```
import os
os.path.expanduser('~/')
```

Thanks,
