### ISSUE TITLE
ETOPO().subset() failing

### ISSUE THREAD

**Issue by biavillasboas** [castelao/oceansdb#2]
Fails if running:

`subset, dims = etopo.subset(lat=lat, lon=lon, var='elevation')`

lat = array([-75, -60, -45, -30,   0,  15,  30,  45,  60,  75])
lon = array([-141.56, -126.56, -111.56,  -96.56,  -81.56,  -66.56,  -51.56,
        -36.56,  -21.56,   -6.56,    8.44,   23.44,   38.44,   53.44,
         68.44,   83.44,   98.44,  113.44,  128.44,  143.44,  158.44,
        173.44,  188.44,  203.44,  218.44,  233.44,  248.44,  263.44,
        278.44,  293.44,  308.44,  323.44,  338.44,  353.44,  368.44,
        383.44,  398.44,  413.44,  428.44,  443.44,  458.44,  473.44,
        488.44,  503.44,  518.44,  533.44,  548.44,  563.44])

**Comment by castelao** [comment]
Working fine with 0.6.1
