### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by sgartzman** [castelao/oceansdb#8]
Thank you very much for this package.

I can't seem to progress in getting topography without an HTTPError.

```
db = oceansdb.ETOPO()
h = db['topography'].extract(lat=17.5, lon=0)
```

I get this error

```
  raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: Not Found
```

Python 2.7.13, oceandsdb 0.8.1

**Comment by castelao** [comment]
Sorry for the delay. I'll be able to check it in a couple of days. Thank you very much for reporting this.

**Comment by castelao** [comment]
@sgartzman , the latest version should work fine. Thank you very much!
